/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionIndexRouteImport } from './routes/submission/index'
import { Route as ResultIndexRouteImport } from './routes/result/index'
import { Route as QuestionsIdIndexRouteImport } from './routes/questions/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionIndexRoute = SubmissionIndexRouteImport.update({
  id: '/submission/',
  path: '/submission/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIndexRoute = ResultIndexRouteImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdIndexRoute = QuestionsIdIndexRouteImport.update({
  id: '/questions/$id/',
  path: '/questions/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultIndexRoute
  '/submission': typeof SubmissionIndexRoute
  '/questions/$id': typeof QuestionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultIndexRoute
  '/submission': typeof SubmissionIndexRoute
  '/questions/$id': typeof QuestionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/result/': typeof ResultIndexRoute
  '/submission/': typeof SubmissionIndexRoute
  '/questions/$id/': typeof QuestionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/result' | '/submission' | '/questions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/result' | '/submission' | '/questions/$id'
  id: '__root__' | '/' | '/result/' | '/submission/' | '/questions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultIndexRoute: typeof ResultIndexRoute
  SubmissionIndexRoute: typeof SubmissionIndexRoute
  QuestionsIdIndexRoute: typeof QuestionsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission/': {
      id: '/submission/'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/': {
      id: '/result/'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id/': {
      id: '/questions/$id/'
      path: '/questions/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof QuestionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultIndexRoute: ResultIndexRoute,
  SubmissionIndexRoute: SubmissionIndexRoute,
  QuestionsIdIndexRoute: QuestionsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
