/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewRouteImport } from './routes/view'
import { Route as SplatRouteImport } from './routes/$'
import { Route as QuizRouteRouteImport } from './routes/_quiz/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSubmissionIndexRouteImport } from './routes/_quiz/submission/index'
import { Route as QuizResultIndexRouteImport } from './routes/_quiz/result/index'
import { Route as QuizQuestionsIndexRouteImport } from './routes/_quiz/questions/index'

const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRouteRoute = QuizRouteRouteImport.update({
  id: '/_quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSubmissionIndexRoute = QuizSubmissionIndexRouteImport.update({
  id: '/submission/',
  path: '/submission/',
  getParentRoute: () => QuizRouteRoute,
} as any)
const QuizResultIndexRoute = QuizResultIndexRouteImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => QuizRouteRoute,
} as any)
const QuizQuestionsIndexRoute = QuizQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => QuizRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/view': typeof ViewRoute
  '/questions': typeof QuizQuestionsIndexRoute
  '/result': typeof QuizResultIndexRoute
  '/submission': typeof QuizSubmissionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/view': typeof ViewRoute
  '/questions': typeof QuizQuestionsIndexRoute
  '/result': typeof QuizResultIndexRoute
  '/submission': typeof QuizSubmissionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_quiz': typeof QuizRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/view': typeof ViewRoute
  '/_quiz/questions/': typeof QuizQuestionsIndexRoute
  '/_quiz/result/': typeof QuizResultIndexRoute
  '/_quiz/submission/': typeof QuizSubmissionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/view' | '/questions' | '/result' | '/submission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/view' | '/questions' | '/result' | '/submission'
  id:
    | '__root__'
    | '/'
    | '/_quiz'
    | '/$'
    | '/view'
    | '/_quiz/questions/'
    | '/_quiz/result/'
    | '/_quiz/submission/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRouteRoute: typeof QuizRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ViewRoute: typeof ViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_quiz': {
      id: '/_quiz'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof QuizRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_quiz/submission/': {
      id: '/_quiz/submission/'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof QuizSubmissionIndexRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/_quiz/result/': {
      id: '/_quiz/result/'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof QuizResultIndexRouteImport
      parentRoute: typeof QuizRouteRoute
    }
    '/_quiz/questions/': {
      id: '/_quiz/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuizQuestionsIndexRouteImport
      parentRoute: typeof QuizRouteRoute
    }
  }
}

interface QuizRouteRouteChildren {
  QuizQuestionsIndexRoute: typeof QuizQuestionsIndexRoute
  QuizResultIndexRoute: typeof QuizResultIndexRoute
  QuizSubmissionIndexRoute: typeof QuizSubmissionIndexRoute
}

const QuizRouteRouteChildren: QuizRouteRouteChildren = {
  QuizQuestionsIndexRoute: QuizQuestionsIndexRoute,
  QuizResultIndexRoute: QuizResultIndexRoute,
  QuizSubmissionIndexRoute: QuizSubmissionIndexRoute,
}

const QuizRouteRouteWithChildren = QuizRouteRoute._addFileChildren(
  QuizRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRouteRoute: QuizRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ViewRoute: ViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
